### ISSUE TITLE
Dependency tracker throws 500 after bom upload

### ISSUE THREAD

**Issue by Lzmog** [sepbit/wpbom#2]
Hello, 

I'm having issue related to bom upload to dependency tracker.
When request is formed and send via curl function, plugin throws only 500 response status code.

So, copied `curl_setopt_array()` function from `src/Controllers/DependencyTrackController.php` and pasted into the php snippet, and tried again with hardcoded parameters, and received same results - 500.

Depedency tracker version: 4.5
Wordpress version: 6.0.3

I modified arguments for `curl_setop_array` function and wanted to push PR, but I wasn't able to push it.
So I'll paste it here:

path: `src/Controllers/DependencyTrackController.php`

```
		curl_setopt_array(
			$curl,
			[
				CURLOPT_URL            => $server . '/api/v1/bom',
				CURLOPT_RETURNTRANSFER => true,
				CURLOPT_ENCODING       => '',
				CURLOPT_MAXREDIRS      => 10,
				CURLOPT_TIMEOUT        => 30,
				CURLOPT_CUSTOMREQUEST  => 'POST',
				CURLOPT_POSTFIELDS     => [
					'bom'         => $bom,
					'autoCreate'  => 'true',
					'projectName' => $project,
				],
				CURLOPT_HTTPHEADER     => [
					'content-type:multipart/form-data',
					"x-api-key:$api_key",
				],
			]
		);
		
```

These code changes worked for me.

P.s. furthermore these changes will improve code readability, because right now its kind hard to understand what is in `CURLOPT_POSTFIELDS`

**Comment by vitoranguia** [comment]
Hello! How are you?
Thank you very much for your contribution.

In your code you used the "autoCreate" parameter, which authorizes the dependency track to create a project if it doesn't exist.
The "autoCreate" functionality requires the "PROJECT_CREATION_UPLOAD" permission.
The plugin was created to require minimal permission, it only requires "BOM_UPLOAD" permission.

In short, I believe you got error 500, because the project was not previously created in the dependency track.
Could you please enter the UUID of an existing project in the "Project" field of the plugin?

If that's the problem, I'll explain the necessary permissions and parameters better in the plugin documentation.

Thanks again!

**Comment by Lzmog** [comment]
Hey! 

I'm doing well, thank you for asking, how about and you? 😄 

> Thank you very much for your contribution.

No problem, I'll try to participate more 😄 and if it's possible to be a contributor

> The "autoCreate" functionality requires the "PROJECT_CREATION_UPLOAD" permission.
> The plugin was created to require minimal permission, it only requires "BOM_UPLOAD" permission.

Understood.

> In short, I believe you got error 500, because the project was not previously created in the dependency track.
> Could you please enter the UUID of an existing project in the "Project" field of the plugin?

Last time when I tried to put existing project name in "Project" input field, upload action responded with 500.

Right now I tried to put uuid in the "Project" input fields, and it **successfully uploaded**. 
So I guess input field name "Project" can be misleading. 😄 I suggest to change into "Project UUID"

By the way, thank you for you help!

**Comment by vitoranguia** [comment]
Documentation will be added in the next release
